### ISSUE TITLE
[bug] discord_js_1.Intents is not a constructor

### ISSUE THREAD

**Issue by ghost** [Androz2091/discord-temp-channels#52]
I recently upgraded my bot to Discord.js v14 and tried to use this module, but it gives me this error whenever I start the bot: 
```js
/home/chamln/Documents/chamlny/discord/aurora/node_modules/discord-temp-channels/lib/index.js:60
        if (!new discord_js_1.Intents(client.options.intents).has('GUILD_VOICE_STATES')) {
             ^
TypeError: discord_js_1.Intents is not a constructor
    at new TempChannelsManager (/home/chamln/Documents/chamlny/discord/aurora/node_modules/discord-temp-channels/lib/index.js:60:14)
    at new AuroraClient (/home/chamln/Documents/chamlny/discord/aurora/structures/AuroraClient.ts:39:22)
    at Object.<anonymous> (/home/chamln/Documents/chamlny/discord/aurora/index.ts:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module.m._compile (/home/chamln/Documents/chamlny/discord/aurora/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Object.require.extensions.<computed> [as .ts] (/home/chamln/Documents/chamlny/discord/aurora/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/home/chamln/Documents/chamlny/discord/aurora/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/home/chamln/Documents/chamlny/discord/aurora/node_modules/ts-node/src/bin.ts:95:10)
    at main (/home/chamln/Documents/chamlny/discord/aurora/node_modules/ts-node/src/bin.ts:55:10)
    at Object.<anonymous> (/home/chamln/Documents/chamlny/discord/aurora/node_modules/ts-node/src/bin.ts:800:3)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
```
I tried to figure it out on my own and found out that the problem is that the module can't check if the discord.js client has the guild voice states intent, no matter if it's provided when initializing the Client or not.
Is it related to breaking changes in discord.js? And if so, will this module support v14 in the future?

**Comment by ghost** [comment]
Update: The issue is probably solved in #53, at least everything works fine for me
